// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: server/proto/click.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player joins the game
type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_server_proto_click_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{0}
}

func (x *JoinGameRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Player data
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalClicks   int32                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	LootCollected []string               `protobuf:"bytes,3,rep,name=loot_collected,json=lootCollected,proto3" json:"loot_collected,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,5,opt,name=experience,proto3" json:"experience,omitempty"`
	LastPlayed    int64                  `protobuf:"varint,6,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_server_proto_click_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetTotalClicks() int32 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *Player) GetLootCollected() []string {
	if x != nil {
		return x.LootCollected
	}
	return nil
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *Player) GetLastPlayed() int64 {
	if x != nil {
		return x.LastPlayed
	}
	return 0
}

// Monster state
type Monster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,2,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	CurrentHealth int32                  `protobuf:"varint,3,opt,name=current_health,json=currentHealth,proto3" json:"current_health,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	LootTable     []string               `protobuf:"bytes,5,rep,name=loot_table,json=lootTable,proto3" json:"loot_table,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monster) Reset() {
	*x = Monster{}
	mi := &file_server_proto_click_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{2}
}

func (x *Monster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monster) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Monster) GetCurrentHealth() int32 {
	if x != nil {
		return x.CurrentHealth
	}
	return 0
}

func (x *Monster) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Monster) GetLootTable() []string {
	if x != nil {
		return x.LootTable
	}
	return nil
}

func (x *Monster) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

// Player attacks monster
type AttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_server_proto_click_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{3}
}

func (x *AttackRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *AttackRequest) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

// Attack response
type AttackResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Player          *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Monster         *Monster               `protobuf:"bytes,2,opt,name=monster,proto3" json:"monster,omitempty"`
	MonsterDefeated bool                   `protobuf:"varint,3,opt,name=monster_defeated,json=monsterDefeated,proto3" json:"monster_defeated,omitempty"`
	LootGained      string                 `protobuf:"bytes,4,opt,name=loot_gained,json=lootGained,proto3" json:"loot_gained,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackResponse) Reset() {
	*x = AttackResponse{}
	mi := &file_server_proto_click_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResponse) ProtoMessage() {}

func (x *AttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResponse.ProtoReflect.Descriptor instead.
func (*AttackResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{4}
}

func (x *AttackResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *AttackResponse) GetMonster() *Monster {
	if x != nil {
		return x.Monster
	}
	return nil
}

func (x *AttackResponse) GetMonsterDefeated() bool {
	if x != nil {
		return x.MonsterDefeated
	}
	return false
}

func (x *AttackResponse) GetLootGained() string {
	if x != nil {
		return x.LootGained
	}
	return ""
}

// Game state update
type GameUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monster       *Monster               `protobuf:"bytes,1,opt,name=monster,proto3" json:"monster,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdate) Reset() {
	*x = GameUpdate{}
	mi := &file_server_proto_click_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdate) ProtoMessage() {}

func (x *GameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdate.ProtoReflect.Descriptor instead.
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{5}
}

func (x *GameUpdate) GetMonster() *Monster {
	if x != nil {
		return x.Monster
	}
	return nil
}

func (x *GameUpdate) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Join game response
type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Monster       *Monster               `protobuf:"bytes,2,opt,name=monster,proto3" json:"monster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_server_proto_click_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_click_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_click_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGameResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *JoinGameResponse) GetMonster() *Monster {
	if x != nil {
		return x.Monster
	}
	return nil
}

var File_server_proto_click_proto protoreflect.FileDescriptor

const file_server_proto_click_proto_rawDesc = "" +
	"\n" +
	"\x18server/proto/click.proto\x12\rmonsterslayer\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\x0fJoinGameRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"\xbd\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x05R\vtotalClicks\x12%\n" +
	"\x0eloot_collected\x18\x03 \x03(\tR\rlootCollected\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x05 \x01(\x05R\n" +
	"experience\x12\x1f\n" +
	"\vlast_played\x18\x06 \x01(\x03R\n" +
	"lastPlayed\"\xbb\x01\n" +
	"\aMonster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"max_health\x18\x02 \x01(\x05R\tmaxHealth\x12%\n" +
	"\x0ecurrent_health\x18\x03 \x01(\x05R\rcurrentHealth\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"loot_table\x18\x05 \x03(\tR\tlootTable\x12!\n" +
	"\flast_updated\x18\x06 \x01(\x03R\vlastUpdated\"H\n" +
	"\rAttackRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\"\xbd\x01\n" +
	"\x0eAttackResponse\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.monsterslayer.PlayerR\x06player\x120\n" +
	"\amonster\x18\x02 \x01(\v2\x16.monsterslayer.MonsterR\amonster\x12)\n" +
	"\x10monster_defeated\x18\x03 \x01(\bR\x0fmonsterDefeated\x12\x1f\n" +
	"\vloot_gained\x18\x04 \x01(\tR\n" +
	"lootGained\"\x8d\x01\n" +
	"\n" +
	"GameUpdate\x120\n" +
	"\amonster\x18\x01 \x01(\v2\x16.monsterslayer.MonsterR\amonster\x12/\n" +
	"\aplayers\x18\x02 \x03(\v2\x15.monsterslayer.PlayerR\aplayers\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"s\n" +
	"\x10JoinGameResponse\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.monsterslayer.PlayerR\x06player\x120\n" +
	"\amonster\x18\x02 \x01(\v2\x16.monsterslayer.MonsterR\amonster2\xf4\x01\n" +
	"\rMonsterSlayer\x12K\n" +
	"\bJoinGame\x12\x1e.monsterslayer.JoinGameRequest\x1a\x1f.monsterslayer.JoinGameResponse\x12L\n" +
	"\rAttackMonster\x12\x1c.monsterslayer.AttackRequest\x1a\x1d.monsterslayer.AttackResponse\x12H\n" +
	"\x11StreamGameUpdates\x12\x16.google.protobuf.Empty\x1a\x19.monsterslayer.GameUpdate0\x01B&Z$grpc-click-slayer/server/proto;protob\x06proto3"

var (
	file_server_proto_click_proto_rawDescOnce sync.Once
	file_server_proto_click_proto_rawDescData []byte
)

func file_server_proto_click_proto_rawDescGZIP() []byte {
	file_server_proto_click_proto_rawDescOnce.Do(func() {
		file_server_proto_click_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_click_proto_rawDesc), len(file_server_proto_click_proto_rawDesc)))
	})
	return file_server_proto_click_proto_rawDescData
}

var file_server_proto_click_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_proto_click_proto_goTypes = []any{
	(*JoinGameRequest)(nil),  // 0: monsterslayer.JoinGameRequest
	(*Player)(nil),           // 1: monsterslayer.Player
	(*Monster)(nil),          // 2: monsterslayer.Monster
	(*AttackRequest)(nil),    // 3: monsterslayer.AttackRequest
	(*AttackResponse)(nil),   // 4: monsterslayer.AttackResponse
	(*GameUpdate)(nil),       // 5: monsterslayer.GameUpdate
	(*JoinGameResponse)(nil), // 6: monsterslayer.JoinGameResponse
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_server_proto_click_proto_depIdxs = []int32{
	1, // 0: monsterslayer.AttackResponse.player:type_name -> monsterslayer.Player
	2, // 1: monsterslayer.AttackResponse.monster:type_name -> monsterslayer.Monster
	2, // 2: monsterslayer.GameUpdate.monster:type_name -> monsterslayer.Monster
	1, // 3: monsterslayer.GameUpdate.players:type_name -> monsterslayer.Player
	1, // 4: monsterslayer.JoinGameResponse.player:type_name -> monsterslayer.Player
	2, // 5: monsterslayer.JoinGameResponse.monster:type_name -> monsterslayer.Monster
	0, // 6: monsterslayer.MonsterSlayer.JoinGame:input_type -> monsterslayer.JoinGameRequest
	3, // 7: monsterslayer.MonsterSlayer.AttackMonster:input_type -> monsterslayer.AttackRequest
	7, // 8: monsterslayer.MonsterSlayer.StreamGameUpdates:input_type -> google.protobuf.Empty
	6, // 9: monsterslayer.MonsterSlayer.JoinGame:output_type -> monsterslayer.JoinGameResponse
	4, // 10: monsterslayer.MonsterSlayer.AttackMonster:output_type -> monsterslayer.AttackResponse
	5, // 11: monsterslayer.MonsterSlayer.StreamGameUpdates:output_type -> monsterslayer.GameUpdate
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_server_proto_click_proto_init() }
func file_server_proto_click_proto_init() {
	if File_server_proto_click_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_click_proto_rawDesc), len(file_server_proto_click_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_click_proto_goTypes,
		DependencyIndexes: file_server_proto_click_proto_depIdxs,
		MessageInfos:      file_server_proto_click_proto_msgTypes,
	}.Build()
	File_server_proto_click_proto = out.File
	file_server_proto_click_proto_goTypes = nil
	file_server_proto_click_proto_depIdxs = nil
}
