// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: click.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client sends clicks
type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        string                 `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_click_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{0}
}

func (x *Click) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Click) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Leaderboard entry
type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        string                 `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_click_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{1}
}

func (x *Score) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Score) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Stream of scores
type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*Score               `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_click_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{2}
}

func (x *Leaderboard) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_click_proto protoreflect.FileDescriptor

const file_click_proto_rawDesc = "" +
	"\n" +
	"\vclick.proto\x12\tclickrace\x1a\x1bgoogle/protobuf/empty.proto\"7\n" +
	"\x05Click\x12\x16\n" +
	"\x06player\x18\x01 \x01(\tR\x06player\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"5\n" +
	"\x05Score\x12\x16\n" +
	"\x06player\x18\x01 \x01(\tR\x06player\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"7\n" +
	"\vLeaderboard\x12(\n" +
	"\x06scores\x18\x01 \x03(\v2\x10.clickrace.ScoreR\x06scores2\x83\x01\n" +
	"\tClickRace\x122\n" +
	"\n" +
	"SendClicks\x12\x10.clickrace.Click\x1a\x10.clickrace.Score(\x01\x12B\n" +
	"\x0eGetLeaderboard\x12\x16.google.protobuf.Empty\x1a\x16.clickrace.Leaderboard0\x01B$Z\"grpc-click-race/server/proto;protob\x06proto3"

var (
	file_click_proto_rawDescOnce sync.Once
	file_click_proto_rawDescData []byte
)

func file_click_proto_rawDescGZIP() []byte {
	file_click_proto_rawDescOnce.Do(func() {
		file_click_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_click_proto_rawDesc), len(file_click_proto_rawDesc)))
	})
	return file_click_proto_rawDescData
}

var file_click_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_click_proto_goTypes = []any{
	(*Click)(nil),         // 0: clickrace.Click
	(*Score)(nil),         // 1: clickrace.Score
	(*Leaderboard)(nil),   // 2: clickrace.Leaderboard
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_click_proto_depIdxs = []int32{
	1, // 0: clickrace.Leaderboard.scores:type_name -> clickrace.Score
	0, // 1: clickrace.ClickRace.SendClicks:input_type -> clickrace.Click
	3, // 2: clickrace.ClickRace.GetLeaderboard:input_type -> google.protobuf.Empty
	1, // 3: clickrace.ClickRace.SendClicks:output_type -> clickrace.Score
	2, // 4: clickrace.ClickRace.GetLeaderboard:output_type -> clickrace.Leaderboard
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_click_proto_init() }
func file_click_proto_init() {
	if File_click_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_click_proto_rawDesc), len(file_click_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_click_proto_goTypes,
		DependencyIndexes: file_click_proto_depIdxs,
		MessageInfos:      file_click_proto_msgTypes,
	}.Build()
	File_click_proto = out.File
	file_click_proto_goTypes = nil
	file_click_proto_depIdxs = nil
}
