/**
 * @fileoverview gRPC-Web generated client stub for clickrace
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: click.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.clickrace = require('./click_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.clickrace.ClickRaceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.clickrace.ClickRacePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.clickrace.Leaderboard>}
 */
const methodDescriptor_ClickRace_GetLeaderboard = new grpc.web.MethodDescriptor(
  '/clickrace.ClickRace/GetLeaderboard',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  proto.clickrace.Leaderboard,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.clickrace.Leaderboard.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.clickrace.Leaderboard>}
 *     The XHR Node Readable Stream
 */
proto.clickrace.ClickRaceClient.prototype.getLeaderboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/clickrace.ClickRace/GetLeaderboard',
      request,
      metadata || {},
      methodDescriptor_ClickRace_GetLeaderboard);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.clickrace.Leaderboard>}
 *     The XHR Node Readable Stream
 */
proto.clickrace.ClickRacePromiseClient.prototype.getLeaderboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/clickrace.ClickRace/GetLeaderboard',
      request,
      metadata || {},
      methodDescriptor_ClickRace_GetLeaderboard);
};


module.exports = proto.clickrace;

