// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// source: click.proto

const jspb = require('google-protobuf');
const goog = jspb;
const global = (function() { return this || (1, eval)('this'); }).call(null);

const proto = {};
proto.monsterslayer = {};

// Join game request
proto.monsterslayer.JoinGameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monsterslayer.JoinGameRequest, jspb.Message);

proto.monsterslayer.JoinGameRequest.prototype.getPlayerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

proto.monsterslayer.JoinGameRequest.prototype.setPlayerName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

// Player data
proto.monsterslayer.Player = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.monsterslayer.Player.repeatedFields_, null);
};
goog.inherits(proto.monsterslayer.Player, jspb.Message);

proto.monsterslayer.Player.repeatedFields_ = [3];

proto.monsterslayer.Player.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

proto.monsterslayer.Player.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

proto.monsterslayer.Player.prototype.getTotalClicks = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

proto.monsterslayer.Player.prototype.setTotalClicks = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

proto.monsterslayer.Player.prototype.getLootCollectedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};

proto.monsterslayer.Player.prototype.setLootCollectedList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};

proto.monsterslayer.Player.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};

proto.monsterslayer.Player.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};

proto.monsterslayer.Player.prototype.getExperience = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

proto.monsterslayer.Player.prototype.setExperience = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

proto.monsterslayer.Player.prototype.getLastPlayed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};

proto.monsterslayer.Player.prototype.setLastPlayed = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};

// Monster data
proto.monsterslayer.Monster = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.monsterslayer.Monster.repeatedFields_, null);
};
goog.inherits(proto.monsterslayer.Monster, jspb.Message);

proto.monsterslayer.Monster.repeatedFields_ = [5];

proto.monsterslayer.Monster.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

proto.monsterslayer.Monster.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

proto.monsterslayer.Monster.prototype.getMaxHealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

proto.monsterslayer.Monster.prototype.setMaxHealth = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

proto.monsterslayer.Monster.prototype.getCurrentHealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

proto.monsterslayer.Monster.prototype.setCurrentHealth = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

proto.monsterslayer.Monster.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};

proto.monsterslayer.Monster.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};

proto.monsterslayer.Monster.prototype.getLootTableList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};

proto.monsterslayer.Monster.prototype.setLootTableList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};

proto.monsterslayer.Monster.prototype.getLastUpdated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};

proto.monsterslayer.Monster.prototype.setLastUpdated = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};

// Attack request
proto.monsterslayer.AttackRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monsterslayer.AttackRequest, jspb.Message);

proto.monsterslayer.AttackRequest.prototype.getPlayerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

proto.monsterslayer.AttackRequest.prototype.setPlayerName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

proto.monsterslayer.AttackRequest.prototype.getDamage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

proto.monsterslayer.AttackRequest.prototype.setDamage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

// Attack response
proto.monsterslayer.AttackResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monsterslayer.AttackResponse, jspb.Message);

proto.monsterslayer.AttackResponse.prototype.getPlayer = function() {
  return /** @type{?proto.monsterslayer.Player} */ (jspb.Message.getWrapperField(this, proto.monsterslayer.Player, 1));
};

proto.monsterslayer.AttackResponse.prototype.setPlayer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

proto.monsterslayer.AttackResponse.prototype.getMonster = function() {
  return /** @type{?proto.monsterslayer.Monster} */ (jspb.Message.getWrapperField(this, proto.monsterslayer.Monster, 2));
};

proto.monsterslayer.AttackResponse.prototype.setMonster = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};

proto.monsterslayer.AttackResponse.prototype.getMonsterDefeated = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};

proto.monsterslayer.AttackResponse.prototype.setMonsterDefeated = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};

proto.monsterslayer.AttackResponse.prototype.getLootGained = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};

proto.monsterslayer.AttackResponse.prototype.setLootGained = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

// Game update
proto.monsterslayer.GameUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.monsterslayer.GameUpdate.repeatedFields_, null);
};
goog.inherits(proto.monsterslayer.GameUpdate, jspb.Message);

proto.monsterslayer.GameUpdate.repeatedFields_ = [2];

proto.monsterslayer.GameUpdate.prototype.getMonster = function() {
  return /** @type{?proto.monsterslayer.Monster} */ (jspb.Message.getWrapperField(this, proto.monsterslayer.Monster, 1));
};

proto.monsterslayer.GameUpdate.prototype.setMonster = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

proto.monsterslayer.GameUpdate.prototype.getPlayersList = function() {
  return /** @type {!Array<!proto.monsterslayer.Player>} */ (jspb.Message.getRepeatedWrapperField(this, proto.monsterslayer.Player, 2));
};

proto.monsterslayer.GameUpdate.prototype.setPlayersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value || []);
};

proto.monsterslayer.GameUpdate.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

proto.monsterslayer.GameUpdate.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

// Join game response
proto.monsterslayer.JoinGameResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monsterslayer.JoinGameResponse, jspb.Message);

proto.monsterslayer.JoinGameResponse.prototype.getPlayer = function() {
  return /** @type{?proto.monsterslayer.Player} */ (jspb.Message.getWrapperField(this, proto.monsterslayer.Player, 1));
};

proto.monsterslayer.JoinGameResponse.prototype.setPlayer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

proto.monsterslayer.JoinGameResponse.prototype.getMonster = function() {
  return /** @type{?proto.monsterslayer.Player} */ (jspb.Message.getWrapperField(this, proto.monsterslayer.Monster, 2));
};

proto.monsterslayer.JoinGameResponse.prototype.setMonster = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};

module.exports = proto.monsterslayer;
