// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// source: click.proto

const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.monsterslayer = {};
proto.monsterslayer.MonsterSlayer = (function () {
  function MonsterSlayer() {}
  MonsterSlayer.serviceName = 'monsterslayer.MonsterSlayer';
  return MonsterSlayer;
}());

proto.monsterslayer.MonsterSlayer.JoinGame = function (request, metadata, callback) {
  if (arguments.length === 2) {
    if (typeof arguments[1] === 'function') {
      callback = arguments[1];
      metadata = {};
    }
  }
  const client = grpc.web.defaultClient;
  const path = '/monsterslayer.MonsterSlayer/JoinGame';
  client.unaryCall(path, request, metadata, callback);
};

proto.monsterslayer.MonsterSlayer.AttackMonster = function (request, metadata, callback) {
  if (arguments.length === 2) {
    if (typeof arguments[1] === 'function') {
      callback = arguments[1];
      metadata = {};
    }
  }
  const client = grpc.web.defaultClient;
  const path = '/monsterslayer.MonsterSlayer/AttackMonster';
  client.unaryCall(path, request, metadata, callback);
};

proto.monsterslayer.MonsterSlayer.StreamGameUpdates = function (request, metadata) {
  const client = grpc.web.defaultClient;
  const path = '/monsterslayer.MonsterSlayer/StreamGameUpdates';
  return client.serverStreaming(path, request, metadata);
};

module.exports = proto.monsterslayer.MonsterSlayer;
